---
title: "eda"
author: "노윤지"
date: "2023-09-14"
output:
  html_document:
    margin:
      top: 0cm
      bottom: 0cm
      left: 0cm
      right: 0cm
---

```{r env, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warnings= FALSE)
library(tidyverse)
library(knitr)
library(gtsummary)
library(labelled)
library(summarytools)
library(kableExtra)
library(magrittr)
library(pander)
library(haven)
```

```{r,warning = FALSE, message = FALSE}
source("/Users/yj.noh/Documents/GitHub/prj-ML-model-LT_OV30/R_code/glm.R")
```

###  **[Table 1.1] **Summary of input varaiables analysts** {.tabset}
```{r, warning=FALSE, message=FALSE}
  
data%>% 
# tbl_strata(
#     strata = outcome,~.x  %>% 
    tbl_summary(
        by = outcome,
        type = all_continuous() ~ "continuous2",
              statistic = all_continuous() ~ c("{mean} ({sd})", "{min}, {max}"),
              missing_text = "(Missing value)", 
              digits = list(all_continuous() ~ c(0, 1), 
                            all_categorical() ~ c(0, 1))) %>%
  add_overall() %>%
  add_p(pvalue_fun = ~style_pvalue(., digits = 3)) %>%
  bold_labels()

```



